#cloud-config

# MapMap Tile Proxy Cloud-Init Configuration (Refactored)
# Scripts are now in the repository for easier maintenance

package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - git
  - htop
  - fail2ban
  - ufw
  - jq

# Create mapmap user
users:
  - name: mapmap
    groups: [sudo, docker]
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJKQ+6iZKKw0eMJbuMTIyoZ9940ecNlac6dqCpy3eiCq vadikas@c57bl6

# Main initialization
runcmd:
  # Clone repository first
  - cd /home/mapmap
  - git clone https://github.com/vadika/mapmap.git
  - chown -R mapmap:mapmap /home/mapmap/mapmap
  
  # Run initialization script from repository
  - /home/mapmap/mapmap/scripts/init-server.sh

write_files:
  # Systemd service for MapMap
  - path: /etc/systemd/system/mapmap.service
    permissions: '0644'
    content: |
      [Unit]
      Description=MapMap Tile Proxy
      After=docker.service
      Requires=docker.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      WorkingDirectory=/home/mapmap/mapmap
      ExecStart=/usr/local/bin/docker-compose -f docker-compose.production.yml up -d
      ExecStop=/usr/local/bin/docker-compose -f docker-compose.production.yml down
      ExecReload=/home/mapmap/mapmap/scripts/deploy-mapmap.sh
      TimeoutStartSec=0
      User=mapmap
      Group=mapmap

      [Install]
      WantedBy=multi-user.target

  # Initial production environment configuration
  - path: /home/mapmap/mapmap/.env
    owner: mapmap:mapmap
    permissions: '0600'
    content: |
      # Production Environment Configuration
      LOG_LEVEL=WARNING
      CACHE_SIZE=10000
      CACHE_TTL=7200
      
      # Security - IMPORTANT: Update these values!
      ALLOWED_ORIGINS=https://yourdomain.com,https://www.yourdomain.com
      ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com
      SECRET_KEY=REPLACE_WITH_SECURE_RANDOM_STRING
      
      # Performance
      WORKERS=4
      MAX_CONNECTIONS=1000
      KEEPALIVE_TIMEOUT=5
      
      # WMTS Endpoints
      WMTS_ENDPOINTS={"latvia": {"url": "https://lvmgeoproxy01.lvm.lv/wmts_b6948e305fb9446985a41b2aee54e07d/wmts", "layer": "public:Topo10DTM", "coordinate_system": "LKS_LVM", "app_id": "lvmgeo.lvm.lv/", "style": "raster", "format": "image/vnd.jpeg-png8"}, "latvia_webmercator": {"url": "https://lvmgeoproxy01.lvm.lv/wmts_b6948e305fb9446985a41b2aee54e07d/wmts", "layer": "public:Topo10DTM", "coordinate_system": "WebMercatorQuad", "app_id": "lvmgeo.lvm.lv/", "style": "raster", "format": "image/vnd.jpeg-png8"}}
      
      # Default endpoint
      DEFAULT_ENDPOINT=latvia_webmercator
      
      # Monitoring
      ENABLE_METRICS=true
      METRICS_PORT=9090
      
      # Rate Limiting
      RATE_LIMIT_ENABLED=true
      RATE_LIMIT_REQUESTS=1000
      RATE_LIMIT_WINDOW=3600

  # Nginx configuration template
  - path: /home/mapmap/mapmap/nginx-ssl.conf
    owner: mapmap:mapmap
    permissions: '0644'
    content: |
      user nginx;
      worker_processes auto;
      error_log /var/log/nginx/error.log warn;
      pid /var/run/nginx.pid;

      events {
          worker_connections 1024;
          use epoll;
          multi_accept on;
      }

      http {
          include /etc/nginx/mime.types;
          default_type application/octet-stream;

          log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for" '
                          'rt=$request_time uct="$upstream_connect_time" '
                          'uht="$upstream_header_time" urt="$upstream_response_time"';

          access_log /var/log/nginx/access.log main;

          sendfile on;
          tcp_nopush on;
          tcp_nodelay on;
          keepalive_timeout 65;
          types_hash_max_size 2048;
          client_max_body_size 1M;

          gzip on;
          gzip_vary on;
          gzip_min_length 1024;
          gzip_types
              text/plain
              text/css
              text/xml
              text/javascript
              application/json
              application/javascript
              application/xml+rss
              application/atom+xml
              image/svg+xml;

          limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
          limit_req_zone $binary_remote_addr zone=tiles:10m rate=100r/s;

          upstream mapmap_backend {
              server mapmap:8000;
              keepalive 32;
          }

          # HTTP server
          server {
              listen 8111;
              server_name yourdomain.com www.yourdomain.com;
              add_header X-Frame-Options "SAMEORIGIN" always;
              add_header X-Content-Type-Options "nosniff" always;
              add_header X-XSS-Protection "1; mode=block" always;
              add_header Referrer-Policy "strict-origin-when-cross-origin" always;

              limit_req zone=api burst=20 nodelay;

              location /health {
                  access_log off;
                  proxy_pass http://mapmap_backend;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

              location /tiles/ {
                  limit_req zone=tiles burst=200 nodelay;
                  
                  proxy_cache_valid 200 1h;
                  proxy_cache_valid 404 1m;
                  add_header X-Cache-Status $upstream_cache_status;

                  proxy_pass http://mapmap_backend;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  
                  proxy_connect_timeout 5s;
                  proxy_send_timeout 10s;
                  proxy_read_timeout 10s;
              }

              location / {
                  proxy_pass http://mapmap_backend;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  
                  proxy_connect_timeout 5s;
                  proxy_send_timeout 30s;
                  proxy_read_timeout 30s;
              }
          }
      }

final_message: |
  🎉 MapMap Tile Proxy has been deployed successfully!
  
  Scripts available in /home/mapmap/mapmap/scripts/:
  - deploy-mapmap.sh: Deploy updates from git
  - monitor-mapmap.sh: Check service status
  
  Next steps:
  1. Update /home/mapmap/mapmap/.env with your domain and secret key
  2. Monitor service: sudo -u mapmap /home/mapmap/mapmap/scripts/monitor-mapmap.sh
  
  Service endpoints:
  - Health: http://your-server-ip:8000/health
  - Tiles: http://your-server-ip:8000/tiles/{z}/{x}/{y}
  - Metrics: http://your-server-ip:8000/metrics
  
  For support, check /home/mapmap/mapmap/DEPLOYMENT.md