#cloud-config

# MapMap Tile Proxy Cloud-Init Configuration
# Deploy MapMap on Ubuntu 22.04+ VPS with Docker and production setup

package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - git
  - htop
  - fail2ban
  - ufw

# Create mapmap user
users:
  - name: mapmap
    groups: [sudo, docker]
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJKQ+6iZKKw0eMJbuMTIyoZ9940ecNlac6dqCpy3eiCq vadikas@c57bl6

# Configure firewall
runcmd:
  # Configure UFW firewall
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow ssh
  - ufw allow 8111/tcp
  - ufw --force enable

  # Install Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker mapmap

  # Install Docker Compose (standalone)
  - curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

  # Clone MapMap repository
  - cd /home/mapmap
  - git clone https://github.com/yourusername/mapmap.git
  - chown -R mapmap:mapmap /home/mapmap/mapmap
  - cd /home/mapmap/mapmap

  # Setup production environment
  - cp .env.production .env
  - chown mapmap:mapmap .env

  # Create directories
  - mkdir -p /home/mapmap/mapmap/logs
  - chown -R mapmap:mapmap /home/mapmap/mapmap

  # Configure fail2ban
  - systemctl enable fail2ban
  - systemctl start fail2ban

write_files:
  # Production environment configuration
  - path: /home/mapmap/mapmap/.env
    owner: mapmap:mapmap
    permissions: '0600'
    content: |
      # Production Environment Configuration
      LOG_LEVEL=WARNING
      CACHE_SIZE=10000
      CACHE_TTL=7200
      
      # Security - IMPORTANT: Update these values!
      ALLOWED_ORIGINS=https://yourdomain.com,https://www.yourdomain.com
      ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com
      SECRET_KEY=REPLACE_WITH_SECURE_RANDOM_STRING
      
      # Performance
      WORKERS=4
      MAX_CONNECTIONS=1000
      KEEPALIVE_TIMEOUT=5
      
      # WMTS Endpoints
      WMTS_ENDPOINTS={"latvia": {"url": "https://lvmgeoproxy01.lvm.lv/wmts_b6948e305fb9446985a41b2aee54e07d/wmts", "layer": "public:Topo10DTM", "coordinate_system": "LKS_LVM", "app_id": "lvmgeo.lvm.lv/", "style": "raster", "format": "image/vnd.jpeg-png8"}, "latvia_webmercator": {"url": "https://lvmgeoproxy01.lvm.lv/wmts_b6948e305fb9446985a41b2aee54e07d/wmts", "layer": "public:Topo10DTM", "coordinate_system": "WebMercatorQuad", "app_id": "lvmgeo.lvm.lv/", "style": "raster", "format": "image/vnd.jpeg-png8"}}
      
      # Default endpoint
      DEFAULT_ENDPOINT=latvia_webmercator
      
      # Monitoring
      ENABLE_METRICS=true
      METRICS_PORT=9090
      
      # Rate Limiting
      RATE_LIMIT_ENABLED=true
      RATE_LIMIT_REQUESTS=1000
      RATE_LIMIT_WINDOW=3600

  

  # Systemd service for MapMap
  - path: /etc/systemd/system/mapmap.service
    permissions: '0644'
    content: |
      [Unit]
      Description=MapMap Tile Proxy
      After=docker.service
      Requires=docker.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      WorkingDirectory=/home/mapmap/mapmap
      ExecStart=/usr/local/bin/docker-compose -f docker-compose.production.yml up -d
      ExecStop=/usr/local/bin/docker-compose -f docker-compose.production.yml down
      TimeoutStartSec=0
      User=mapmap
      Group=mapmap

      [Install]
      WantedBy=multi-user.target

  # Deployment script
  - path: /home/mapmap/deploy-mapmap.sh
    owner: mapmap:mapmap
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e

      echo "🚀 Deploying MapMap Tile Proxy..."

      # Navigate to project directory
      cd /home/mapmap/mapmap

      # Update repository
      echo "📥 Updating repository..."
      git pull origin main

      # Build and start services
      echo "🐳 Building and starting Docker services..."
      docker-compose -f docker-compose.production.yml build --no-cache
      docker-compose -f docker-compose.production.yml up -d

      # Wait for services to start
      echo "⏳ Waiting for services to start..."
      sleep 30

      # Health check
      echo "🔍 Checking service health..."
      if curl -f http://localhost:8000/health; then
          echo "✅ MapMap is running successfully!"
          echo "🌐 Service available at: https://$(hostname -f)"
      else
          echo "❌ Health check failed!"
          docker-compose -f docker-compose.production.yml logs
          exit 1
      fi

  

  # Monitoring script
  - path: /home/mapmap/monitor-mapmap.sh
    owner: mapmap:mapmap
    permissions: '0755'
    content: |
      #!/bin/bash

      echo "📊 MapMap Service Status"
      echo "======================="

      cd /home/mapmap/mapmap

      # Docker containers status
      echo "🐳 Container Status:"
      docker-compose -f docker-compose.production.yml ps

      echo ""
      echo "🔍 Health Check:"
      curl -s http://localhost:8000/health | jq . || echo "❌ Health check failed"

      echo ""
      echo "📈 Metrics (if enabled):"
      curl -s http://localhost:8000/metrics | grep -E "mapmap_.*_total" || echo "Metrics not available"

      echo ""
      echo "💾 System Resources:"
      echo "Memory: $(free -h | grep Mem | awk '{print $3 "/" $2}')"
      echo "Disk: $(df -h / | tail -1 | awk '{print $3 "/" $2 " (" $5 " used)"}')"
      echo "Load: $(uptime | cut -d',' -f3-)"

final_message: |
  🎉 MapMap Tile Proxy has been deployed successfully!
  
  Next steps:
  1. Update /home/mapmap/mapmap/.env with your domain and secret key
  2. Enable systemd service: sudo systemctl enable mapmap
  3. Monitor service: sudo -u mapmap /home/mapmap/monitor-mapmap.sh
  
  Service endpoints:
  - Health: http://your-server-ip:8000/health
  - Tiles: http://your-server-ip:8000/tiles/{z}/{x}/{y}
  - Metrics: http://your-server-ip:8000/metrics
  
  Security reminders:
  - Change SSH keys and passwords
  - Update ALLOWED_ORIGINS and ALLOWED_HOSTS in .env
  - Generate a secure SECRET_KEY
  - Configure DNS to point to this server
  
  For support, check /home/mapmap/mapmap/DEPLOYMENT.md