version: '3.8'

services:
  mapmap:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: mapmap-production
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=WARNING
      - CACHE_SIZE=10000
      - CACHE_TTL=7200
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    networks:
      - mapmap-network

  # Optional: Redis for distributed caching
  redis:
    image: redis:7-alpine
    container_name: mapmap-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - mapmap-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: mapmap-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - mapmap
    networks:
      - mapmap-network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'

volumes:
  redis_data:
  nginx_logs:

networks:
  mapmap-network:
    driver: bridge